## Arithmetic Operations

In [1]:
r = 1500
t = 0.2

total = r * (1 + t)
total

1800.0

## List

In [2]:
l = [10, 20, 30, 40]

In [3]:
l = [10, "test233", "mest", 50]

In [4]:
l

[10, 'test233', 'mest', 50]

In [6]:
len(l[1])

7

In [7]:
len(l)

4

In [9]:
l[0] = 11
l

[11, 'test233', 'mest', 50]

## Tuple

In [10]:
t = (10, 12, 13)

## Set

In [11]:
my_list = [1, 2, 3, 4, 5, 5, 5]

In [13]:
my_set = set(my_list)
my_set

{1, 2, 3, 4, 5}

In [15]:
a = {1, 1, 2, 3, 4, 5}
b = {4, 5, 6, 7, 8}

In [16]:
a.intersection(b)

{4, 5}

## Dictionary

In [17]:
# key value pairs
customers = {'Alice': 25,
             'Bob': 30,
             'Charlie': 35}

In [18]:
customers['Alice']

25

In [27]:
customer1 = {'name': 'Alice', 'age': 25, 'city': 'NY', 'segment': 'Premium'}
customer1

{'name': 'Alice', 'age': 25, 'city': 'NY', 'segment': 'Premium'}

In [26]:
#Bob
customer2 = {'name': 'Bob', 'age': 30, 'city': 'CA', 'segment': 'Standart'}
customer2

{'name': 'Bob', 'age': 30, 'city': 'CA', 'segment': 'Standart'}

In [25]:
#Bob
customer3 = {'name': 'Charlie', 'age': 325, 'city': 'Chicago', 'segment': 'Premium'}
customer3

{'name': 'Charlie', 'age': 325, 'city': 'Chicago', 'segment': 'Premium'}

In [28]:
list_of_customers = [customer1, customer2, customer3]

In [30]:
list_of_customers

[{'name': 'Alice', 'age': 25, 'city': 'NY', 'segment': 'Premium'},
 {'name': 'Bob', 'age': 30, 'city': 'CA', 'segment': 'Standart'},
 {'name': 'Charlie', 'age': 325, 'city': 'Chicago', 'segment': 'Premium'}]

In [31]:
list_of_customers[0]['name']

'Alice'

In [34]:
list(list_of_customers[0].keys())

['name', 'age', 'city', 'segment']

In [ ]:
l = [10, 20, 30, 40]
d = {'key', 'value'}

In [ ]:
import pandas as pd

In [92]:
data = {'name' : ['Alice', 'Bob', 'Charlie', 'David', 'Armen'],
        'age': [30, 25, 28, 40, 18],
        'city': ['New York', 'Los Angeles', 'Chicago', 'Boston', 'San Francisco']}

In [93]:
data['name']
data['age']

[30, 25, 28, 40, 18]

In [94]:
df = pd.DataFrame(data)

In [95]:
df.head()

      name  age           city
0    Alice   30       New York
1      Bob   25    Los Angeles
2  Charlie   28        Chicago
3    David   40         Boston
4    Armen   18  San Francisco

In [96]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   age     5 non-null      int64
 2   city    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [97]:
df.shape

f"{df.shape[0]} rows {df.shape[1]} columns"

'5 rows 3 columns'

In [98]:
list(df.columns)

['name', 'age', 'city']

In [99]:
df.head(2)

    name  age         city
0  Alice   30     New York
1    Bob   25  Los Angeles

In [100]:
df['name']

0      Alice
1        Bob
2    Charlie
3      David
4      Armen
Name: name, dtype: str

In [101]:
df[['name', 'age']]

      name  age
0    Alice   30
1      Bob   25
2  Charlie   28
3    David   40
4    Armen   18

In [116]:
df['State'] = 'Unknown'

In [103]:
df.head()

      name  age           city    State
0    Alice   30       New York  Unknown
1      Bob   25    Los Angeles  Unknown
2  Charlie   28        Chicago  Unknown
3    David   40         Boston  Unknown
4    Armen   18  San Francisco  Unknown

In [114]:
df['age'] = [int(i*0.9) for i in df['age']]
df.head()

      name  age           city
0    Alice   27       New York
1      Bob   22    Los Angeles
2  Charlie   25        Chicago
3    David   36         Boston
4    Armen   16  San Francisco

In [117]:
df.drop('State', axis=1)

      name  age           city
0    Alice   27       New York
1      Bob   22    Los Angeles
2  Charlie   25        Chicago
3    David   36         Boston
4    Armen   16  San Francisco

In [118]:
df[df['age'] > 30]

    name  age    city    State
3  David   36  Boston  Unknown

In [1]:
r = 100
t = 0.2

total = r * (1 + t)
total

120.0

In [2]:
100 > 50
100 == 50
100 != 50

True

In [3]:
print((100 > 50) and (20 < 30))

True

In [4]:
sales = [100, 200,150, 200]
sales

[100, 200, 150, 200]

In [7]:
sales = [0]
sales = [-1]

In [1]:
a = 6
b = 5

In [ ]:
a = a + b

In [7]:
sales = [100, 200, 150, 200]
sales

[100, 200, 150, 200]

In [2]:
sales[0]

100

In [3]:
sales[-1]

400

In [ ]:
sales.append(300)
sales[1] = 250
sales

[100, 250, 150, 200, 300]

In [9]:
sales.remove(150)
sales

[100, 250, 200, 300]

In [10]:
len(sales)

4

In [11]:
total = 0
for value in sales:
    total += value

total

850

In [12]:
coordinates = (40.18, 44.51)
coordinates

(40.18, 44.51)

In [14]:
customer_ids = {1, 2, 3, 3, 4}
customer_ids

{1, 2, 3, 4}

In [16]:
segment_a = {1, 2, 3}
segment_b = {3, 4, 5}

segment_a.intersection(segment_b)

{3}

In [18]:
customer = {
    'name': "Anna",
    "revenue": 150,
    "city": "Yerevan"
}
customer

{'name': 'Anna', 'revenue': 150, 'city': 'Yerevan'}

In [20]:
customer["revenue"]

150

In [21]:
customer["segment"] = "Premium"
customer["revenue"] = 200
customer

{'name': 'Anna', 'revenue': 200, 'city': 'Yerevan', 'segment': 'Premium'}

In [22]:
del customer["city"]

customer

{'name': 'Anna', 'revenue': 200, 'segment': 'Premium'}

In [23]:
customers = [
    {"name": "Anna", "revenue": 150},
    {"name": "David", "revenue": 220},
    {"name": "Mariam", "revenue": 90},
]
customers

[{'name': 'Anna', 'revenue': 150},
 {'name': 'David', 'revenue': 220},
 {'name': 'Mariam', 'revenue': 90}]

In [24]:
import pandas as pd

data = {
    "name": ["Anna", "David", "Mariam"],
    "revenue": [150, 220, 90],
    "city": ["Yerevan", "Tbilisi", "Warsaw"]
}

df = pd.DataFrame(data)
df

     name  revenue     city
0    Anna      150  Yerevan
1   David      220  Tbilisi
2  Mariam       90   Warsaw

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      str
 1   revenue  3 non-null      int64
 2   city     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

In [27]:
df.shape

(3, 3)

In [28]:
df.columns

Index(['name', 'revenue', 'city'], dtype='str')

In [29]:
df["revenue"]

0    150
1    220
2     90
Name: revenue, dtype: int64

In [35]:
df[["name", "revenue"]]

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

In [36]:
t = 0.2
df["revenue_after_tax"] = df["revenue"] * (1 - t)
df

     name  revenue     city  revenue_after_tax
0    Anna      150  Yerevan              120.0
1   David      220  Tbilisi              176.0
2  Mariam       90   Warsaw               72.0

In [37]:
df.drop("city", axis=1)

     name  revenue  revenue_after_tax
0    Anna      150              120.0
1   David      220              176.0
2  Mariam       90               72.0

In [38]:
df.drop("city", axis=1)
df

     name  revenue     city  revenue_after_tax
0    Anna      150  Yerevan              120.0
1   David      220  Tbilisi              176.0
2  Mariam       90   Warsaw               72.0

In [39]:
df

     name  revenue     city  revenue_after_tax
0    Anna      150  Yerevan              120.0
1   David      220  Tbilisi              176.0
2  Mariam       90   Warsaw               72.0

In [40]:
df[df["revenue"] > 100]

    name  revenue     city  revenue_after_tax
0   Anna      150  Yerevan              120.0
1  David      220  Tbilisi              176.0

In [41]:
df.loc[df["revenue"] < 100, "segment"] = "Low"
df.loc[df["revenue"] >= 100, "segment"] = "High"
df

     name  revenue     city  revenue_after_tax segment
0    Anna      150  Yerevan              120.0    High
1   David      220  Tbilisi              176.0    High
2  Mariam       90   Warsaw               72.0     Low

In [45]:
revenue = 150

if revenue > 100:
    print("High revenue")
else:
    print("Low revenue")

High revenue

In [48]:
revenue = 150

if revenue > 100:
    print("High revenue")

print("Analysis complete")

High revenue
Analysis complete

In [49]:
revenue = 180

if revenue > 200:
    print("Very high revenue")
elif revenue > 100:
    print("High revenue")
elif revenue > 50:
    print("Medium revenue")
else:
    print("Low revenue")

High revenue

In [52]:
revenue = 150
is_active = True

if revenue > 100 and is_active:
    print("Target customer")

Target customer

In [53]:
is_active = False
if not is_active:
    print("Customer is inactive")

Customer is inactive

In [55]:
revenue = 150
region = "EU"

if revenue > 100:
    if region == "EU":
        print("High EU revenue")
    else:
        print("High non-EU revenue")

High EU revenue

In [56]:
sales = [100, 200, 150]

for i in sales:
    print(i)

100
200
150

In [60]:
sales = [100, 200, 150]
total = 0

for i in sales:
    total += i
total

450

In [61]:
sales = [100, 200, 150, 50]

for i in sales:
    if i > 120:
        print("High sales:", i)

High sales: 200
High sales: 150

In [66]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

# for i in customer:
#     print(i, ":", customer[i])

for key, value in customer.items():
    print(key, value)

name Anna
revenue 150
city Yerevan

In [67]:
for i in range(5):
    print(i)

0
1
2
3
4

In [68]:
for i in range(3):
    for j in range(2):
        print("i=", i, ", j=", j)

i= 0 , j= 0
i= 0 , j= 1
i= 1 , j= 0
i= 1 , j= 1
i= 2 , j= 0
i= 2 , j= 1

In [70]:
sales = [100, 200, 150]
new_sales = []

for i in sales:
    new_sales.append(i * 1.2)

new_sales

[120.0, 240.0, 180.0]

In [71]:
sales = [100, 200, 150]

new_sales = [i * 1.2 for i in sales]
new_sales

[120.0, 240.0, 180.0]

In [72]:
sales = [100, 200, 150, 50]

high_sales = [i for i in sales if i > 120]
high_sales

[200, 150]

In [74]:
sales = [100, 200, 150, 50]

labels = ["high" if i > 120 else "Low" for i in sales]
labels

['Low', 'high', 'high', 'Low']