In [ ]:
revenues = [120, 250, 80, 310, 95]

## Create a new list with revenues after applying 10% tax.
revenue_after_tax = [i * 0.9 for i in revenues]
revenue_after_tax

[108.0, 225.0, 72.0, 279.0, 85.5]

In [ ]:
## Create a list containing only revenues greater than 100.
greater_than_100 = [i for i in revenues if i > 100 ]
greater_than_100

[120, 250, 310]

In [ ]:
## Create a list labeling each revenue as "High" if > 200, otherwise "Normal".
labels = ["High" if i > 200 else "Normal" for i in revenues]
labels

['Normal', 'High', 'Normal', 'High', 'Normal']

## Part 1

In [6]:
revenues = [120, 250, 80, 310, 95]
tax_rate = 0.18
discount_rate = 0.10

In [ ]:
## Compute revenues including tax.
revenue_after_tax = [i * (1 + 0.18) for i in revenues]
revenue_after_tax

[141.6, 295.0, 94.39999999999999, 365.79999999999995, 112.1]

In [ ]:
## Compute final revenues after tax and discount.
final_revenue = [i * (1 + tax_rate) * (1 - discount_rate) for i in revenues]
final_revenue

[127.44, 265.5, 84.96, 329.21999999999997, 100.89]

In [ ]:
## Create a Boolean list indicating whether revenue > 100.
revenue_above_100 = [i > 100 for i in revenues]
revenue_above_100

[True, True, False, True, False]

In [ ]:

## Create a Boolean list indicating whether revenue is between 100 and 300.
revenue_between_n = [i >= 100 and i <=  300 for i in revenues]
revenue_between_n

[True, True, False, False, False]

## Parentheses affect the order of operations in calculations.
- In math and Python, multiplication and division are done before addition and subtraction.
- If we want a certain operation to happen first, we use parentheses.

## Part 2

In [ ]:
sales = [120, 250, 80, 310, 95]
total = 0

## Total revenue
for i in sales:
    total += i
total

855

In [ ]:
## Average revenue
avg = 0
for i in sales:
    avg = total / len(sales)
avg

171.0

In [24]:
## Maximum value
max = sales[0]

for i in sales:
    if i > max:
        max = i
max

310

In [28]:
## How many values are greater than 150
n = 0

for i in sales:
    if i > 150:
        n += 1
n

2

In [29]:
## New list of revenues after adding 5% commission
revenue_after_commission = [i * 1.05 for i in sales]
revenue_after_commission

[126.0, 262.5, 84.0, 325.5, 99.75]

## Part 3

In [7]:
## Create a list of segment labels.
segments = []

for i in revenues:
    if i > 250:
        segments.append("Premium")
    elif i  > 100 and i <= 250:
        segments.append("Standard")
    else:
        segments.append("Low")
segments

['Standard', 'Standard', 'Low', 'Premium', 'Low']

In [8]:
premium_count = 0
standard_count = 0
low_count = 0

for i in segments:
    if i == "Premium":
        premium_count += 1
    elif i == "Standard":
        standard_count += 1
    elif i == "Low":
        low_count += 1

premium_count, standard_count, low_count

(1, 2, 2)

- Python checks conditions in order
- After the first True, the rest are ignored
- If the order is wrong, the segmentation will be incorrect

## Part 4

In [2]:
customer_ids = [1, 2, 3, 3, 4, 5, 5, 6]
unique_customer_ids = list(set(customer_ids))
unique_customer_ids

[1, 2, 3, 4, 5, 6]

In [3]:
original_length = len(customer_ids)
unique_length = len(unique_customer_ids)

print("Original Length:", original_length)
print("Length after deduplication:", unique_length)

Original Length: 8
Length after deduplication: 6

## Why Sets are Unordered in Python
### In Python, a set is a collection type that stores unique elements. Unlike lists or tuples, sets do not preserve the order of elements.

### Reason:
- Python sets are implemented as hash tables.
- When you add an element to a set, Python computes a hash value for that element.
- The element is then stored in a position determined by its hash, not by the order you inserted it.
- As a result, when you iterate over a set or convert it back to a list, the original insertion order may be different.

## Part 5

In [9]:
customer = {
    "name": "Anna",
    "revenue": 250,
    "city": "Yerevan"
}

In [10]:
## Add a new key "segment" based on revenue.
if customer["revenue"] > 250:
    customer["segment"] = "Premium"
elif customer["revenue"] > 100 and customer["revenue"] <= 250:
    customer["segment"] = "Standard"
else:
    customer["segment"] = "Low"
customer

{'name': 'Anna', 'revenue': 250, 'city': 'Yerevan', 'segment': 'Standard'}

In [11]:
customer["revenue"] = 300
customer

{'name': 'Anna', 'revenue': 300, 'city': 'Yerevan', 'segment': 'Standard'}

In [12]:
del customer["city"]
customer

{'name': 'Anna', 'revenue': 300, 'segment': 'Standard'}

In [15]:
for key, value in customer.items():
    print(f"{key}: {value}")

name: Anna
revenue: 300
segment: Standard

## A dictionary in Python stores data as key-value pairs, making it perfect for structured information.

## Part 6

In [16]:
revenues = [120, 250, 80, 310, 95]
revenues

[120, 250, 80, 310, 95]

In [ ]:
## Create a list of revenues after 10% tax.
revenue_after_tax = [i * 1.1 for i in revenues]
revenue_after_tax

[132.0, 275.0, 88.0, 341.0, 104.50000000000001]

In [ ]:
## Create a list of revenues greater than 100.
revenues_greater_than_100 = [i for i in revenues if i > 100]
revenues_greater_than_100

[120, 250, 310]

In [22]:
labels = ["High" if i > 200 else "Normal" for i in revenues]
labels

['Normal', 'High', 'Normal', 'High', 'Normal']

## List Comprehension vs For Loop
### For Loop 
    - Standard way to build lists.
    - More verbose, but often easier to read for beginners.
    - Good for complex logic or multiple steps.
### List Comprehension
    - Shorter and more compact.
    - Works well for simple transformations.
    - Can be less readable for very complex operations.

## Part 7

In [24]:
import pandas as pd

data = {
    "revenue" : revenues
}

df = pd.DataFrame(data)
df

   revenue
0      120
1      250
2       80
3      310
4       95

In [ ]:
# Add column "revenue_after_tax".
t = 0.2
df["revenue_after_tax"] = df["revenue"] * (1 - t)
df

   revenue  revenue_after_tax
0      120               96.0
1      250              200.0
2       80               64.0
3      310              248.0
4       95               76.0

In [ ]:
# Add column "segment" using conditional logic.
segments = []

for i in df["revenue"]:
    if i > 250:
        segments.append("Premium")
    elif i > 100 and i <= 250:
        segments.append("Standard")
    else:
        segments.append("Low")

df["segment"] = segments
df

   revenue  revenue_after_tax   segment
0      120               96.0  Standard
1      250              200.0  Standard
2       80               64.0       Low
3      310              248.0   Premium
4       95               76.0       Low

In [40]:
# Filter rows where revenue > 100.
df[df["revenue"] > 100]

   revenue  revenue_after_tax   segment
0      120               96.0  Standard
1      250              200.0  Standard
3      310              248.0   Premium

In [42]:
df.drop("revenue_after_tax", axis=1)

   revenue   segment
0      120  Standard
1      250  Standard
2       80       Low
3      310   Premium
4       95       Low

In [43]:
df.shape

(5, 3)

## Pandas works on the whole column at once, no need to loop through each row.