## Unziping File

In [2]:
import zipfile
with zipfile.ZipFile("../data/raw/Archive.zip", "r") as zip_ref:
    zip_ref.extractall("../data/raw")

## Installing Packages

In [3]:
import pandas as pd

In [4]:
## Reading data
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [5]:
df_orders.rename(columns={'order_number':'order_n'}, inplace=True)

In [6]:
df_orders.shape

(3421083, 7)

In [7]:
## list of columns
df_orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_n', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')

In [8]:
df_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                str
 3   order_n                 int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), str(1)
memory usage: 182.7 MB

In [9]:
df_orders.dtypes

order_id                    int64
user_id                     int64
eval_set                      str
order_n                     int64
order_dow                   int64
order_hour_of_day           int64
days_since_prior_order    float64
dtype: object

In [10]:
## summary statisctics
df_orders.describe()

,order_id,user_id,order_n,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [11]:
df_orders.drop(columns = ['eval_set'], inplace = True)

In [12]:
df_orders.columns

Index(['order_id', 'user_id', 'order_n', 'order_dow', 'order_hour_of_day',
       'days_since_prior_order'],
      dtype='str')

In [13]:
df_orders_new = df_orders.assign(
    is_weekend = df_orders["order_dow"].isin([0, 6]),
    is_morning = df_orders["order_hour_of_day"] < 12,
    is_premium = df_orders["days_since_prior_order"] <= 7
)

In [14]:
del df_orders

In [15]:
df_orders_new.head()

,order_id,user_id,order_n,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning,is_premium
0,2539329,1,1,2,8,NaN,False,True,False
1,2398795,1,2,3,7,15.0,False,True,False
2,473747,1,3,3,12,21.0,False,False,False
3,2254736,1,4,4,7,29.0,False,True,False
4,431534,1,5,4,15,28.0,False,False,False

In [16]:
df_orders_new['days_since_prior_order'] = df_orders_new['days_since_prior_order'].fillna(0)

In [17]:
df_orders_new.head()

,order_id,user_id,order_n,order_dow,order_hour_of_day,days_since_prior_order,is_weekend,is_morning,is_premium
0,2539329,1,1,2,8,0.0,False,True,False
1,2398795,1,2,3,7,15.0,False,True,False
2,473747,1,3,3,12,21.0,False,False,False
3,2254736,1,4,4,7,29.0,False,True,False
4,431534,1,5,4,15,28.0,False,False,False

In [18]:
df_orders_new.to_csv('../data/processed/order.csv', index = False)

In [19]:
df_products = pd.read_csv('../data/raw/products.csv')
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [20]:
df_products.shape

(49693, 5)

In [21]:
df_products.drop(columns=['aisle_id'], inplace= True)

In [22]:
df_products.head()

,product_id,product_name,department_id,prices
0,1,Chocolate Sandwich Cookies,19,5.8
1,2,All-Seasons Salt,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,1,10.5
4,5,Green Chile Anytime Sauce,13,4.3

In [36]:
df_departments = pd.read_csv('../data/raw/departments.csv')
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [25]:
df_departments.T

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [26]:
df_dep_t = df_departments.T
df_dep_t.head()

                        0
department_id  department
1                  frozen
2                   other
3                  bakery
4                 produce

In [27]:
df_departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  1 non-null      str
 1   1              1 non-null      str
 2   2              1 non-null      str
 3   3              1 non-null      str
 4   4              1 non-null      str
 5   5              1 non-null      str
 6   6              1 non-null      str
 7   7              1 non-null      str
 8   8              1 non-null      str
 9   9              1 non-null      str
 10  10             1 non-null      str
 11  11             1 non-null      str
 12  12             1 non-null      str
 13  13             1 non-null      str
 14  14             1 non-null      str
 15  15             1 non-null      str
 16  16             1 non-null      str
 17  17             1 non-null      str
 18  18             1 non-null      str
 19  19             1 non-null      str
 20  20             1 non-null      str
 21  21             1 non-null      str
dtypes: str(22)
memory usage: 308.0 bytes

In [28]:
df_products.reset_index()

,index,product_id,product_name,department_id,prices
0,0,1,Chocolate Sandwich Cookies,19,5.8
1,1,2,All-Seasons Salt,13,9.3
2,2,3,Robust Golden Unsweetened Oolong Tea,7,4.5
3,3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,1,10.5
4,4,5,Green Chile Anytime Sauce,13,4.3
...,...,...,...,...,...
49688,49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",5,5.3
49689,49689,49685,En Croute Roast Hazelnut Cranberry,1,3.1
49690,49690,49686,Artisan Baguette,3,7.8
49691,49691,49687,Smartblend Healthy Metabolism Dry Cat Food,8,4.7
49692,49692,49688,Fresh Foaming Cleanser,11,13.5

In [38]:
df_dep_t.reset_index(inplace=True)

ValueError: cannot insert level_0, already exists

In [31]:
new_header = df_dep_t.iloc[0]

In [32]:
df_dep_t_new = df_dep_t[1:]

In [33]:
col_names = df_departments.iloc[0]
col_names

department_id         department
1                         frozen
2                          other
3                         bakery
4                        produce
5                        alcohol
6                  international
7                      beverages
8                           pets
9                dry goods pasta
10                          bulk
11                 personal care
12                  meat seafood
13                        pantry
14                     breakfast
15                  canned goods
16                    dairy eggs
17                     household
18                        babies
19                        snacks
20                          deli
21                       missing
Name: 0, dtype: str

In [34]:
#Setting the new header:
df_dep_t_new.columns = new_header

df_dep_t_new.head()

0 department_id department
1             1     frozen
2             2      other
3             3     bakery
4             4    produce
5             5    alcohol

In [39]:
df_dep_t_new.to_csv("../data/processed/departments_t.csv", index=False)