In [ ]:
# Import pandas library for data manipulation
import pandas as pd

In [6]:
data = ['customers.csv', 'states.csv']

URL = 'https://raw.githubusercontent.com/hovhannisyan91/aca/refs/heads/main/lab/python/data/raw/'

ldf = []
for i in data: 
    df = pd.read_csv(URL+i)
    # քանի որ ցանկանում ենք նաև միացնել տվյալները մենք կարող ենք դա անել միանգամից՝ նախ սկզբում պահելով այն լիստի մեջ
    ldf.append(df)

In [7]:
df_customers = ldf[0]
df_states = ldf[1]

In [8]:
df_customers.head()

,user_id,First Name,Surnam,Gender,STATE,Age,date_joined,n_dependants,fam_status,income
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374

In [10]:
df_states.head()

           state     region     division
0    Connecticut  Northeast  New England
1          Maine  Northeast  New England
2  Massachusetts  Northeast  New England
3  New Hampshire  Northeast  New England
4   Rhode Island  Northeast  New England

In [11]:
df_customers.rename(columns={'STATE':'state'}, inplace=True)

In [12]:
df_customers_states = df_customers.merge(
    df_states,
    on = 'state')
df_customers_states.head()

,user_id,First Name,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665,Midwest,West North Central
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285,West,Mountain
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568,West,Mountain
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049,Midwest,West North Central
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374,South,South Atlantic

In [14]:
df_customers_states.to_csv("../data/processed/customer_states.csv", index=False)