In [1]:
import pandas as pd

In [2]:
products = pd.read_csv("../data/raw/products.csv")
departments = pd.read_csv("../data/processed/departments_t.csv")

In [3]:
products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [4]:
departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [5]:
df_products_departments = pd.merge(
    products,
    departments,
    on = "department_id",
    how = "left",
    # indicator = True
)
df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks
1,2,All-Seasons Salt,104,13,9.3,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry

In [6]:
# df_products_departments["_merge"].value_counts()

In [7]:
df_products_departments.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
 5   department     49693 non-null  str
dtypes: float64(1), int64(3), str(2)
memory usage: 4.2 MB

In [8]:
df_products_departments.shape

(49693, 6)

In [9]:
order_train = pd.read_csv("../data/processed/orders_train.csv")
order_products_train = pd.read_csv("../data/raw/order_products_train.csv")

In [10]:
order_train.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,10,1187899,1,train,11,4,8,14.0
1,25,1492625,2,train,15,1,11,30.0
2,49,2196797,5,train,5,0,11,6.0
3,74,525192,7,train,21,2,11,6.0
4,78,880375,8,train,4,1,14,10.0

In [11]:
order_products_train.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [12]:
df_train_transaction = pd.merge(
    order_train,
    order_products_train,
    on = "order_id",
    how = "left",
    # indicator = True
)
df_train_transaction.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,10,1187899,1,train,11,4,8,14.0,196,1,1
1,10,1187899,1,train,11,4,8,14.0,25133,2,1
2,10,1187899,1,train,11,4,8,14.0,38928,3,1
3,10,1187899,1,train,11,4,8,14.0,26405,4,1
4,10,1187899,1,train,11,4,8,14.0,39657,5,1

In [13]:
# df_train_transaction["_merge"].value_counts()

In [14]:
df_train_transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384617 entries, 0 to 1384616
Data columns (total 11 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Unnamed: 0              1384617 non-null  int64
 1   order_id                1384617 non-null  int64
 2   user_id                 1384617 non-null  int64
 3   eval_set                1384617 non-null  str
 4   order_number            1384617 non-null  int64
 5   order_dow               1384617 non-null  int64
 6   order_hour_of_day       1384617 non-null  int64
 7   days_since_prior_order  1384617 non-null  float64
 8   product_id              1384617 non-null  int64
 9   add_to_cart_order       1384617 non-null  int64
 10  reordered               1384617 non-null  int64
dtypes: float64(1), int64(9), str(1)
memory usage: 123.0 MB

In [15]:
df_train_transaction.shape

(1384617, 11)

In [16]:
aisles = pd.read_csv("../data/raw/aisles.csv")
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [17]:
df_products_enriched = pd.merge(
    df_products_departments,
    aisles,
    on = "aisle_id",
    how = "left",
    # indicator = True
)
df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.3,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry,marinades meat preparation

In [18]:
# df_products_enriched["_merge"].value_counts()

In [19]:
df_products_enriched.info()

<class 'pandas.DataFrame'>
RangeIndex: 49693 entries, 0 to 49692
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49693 non-null  int64
 1   product_name   49677 non-null  str
 2   aisle_id       49693 non-null  int64
 3   department_id  49693 non-null  int64
 4   prices         49693 non-null  float64
 5   department     49693 non-null  str
 6   aisle          49693 non-null  str
dtypes: float64(1), int64(3), str(3)
memory usage: 5.2 MB

In [20]:
df_products_enriched.shape

(49693, 7)

In [21]:
df_train_analytic = pd.merge(
    df_train_transaction,
    df_products_enriched,
    on = "product_id",
    how = "left",
    # indicator = True
)
df_train_analytic.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,10,1187899,1,train,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,beverages,soft drinks
1,10,1187899,1,train,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,10,1187899,1,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,10,1187899,1,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,10,1187899,1,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

In [22]:
# df_train_analytic["_merge"].value_counts()

In [23]:
df_train_analytic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1384706 entries, 0 to 1384705
Data columns (total 17 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Unnamed: 0              1384706 non-null  int64
 1   order_id                1384706 non-null  int64
 2   user_id                 1384706 non-null  int64
 3   eval_set                1384706 non-null  str
 4   order_number            1384706 non-null  int64
 5   order_dow               1384706 non-null  int64
 6   order_hour_of_day       1384706 non-null  int64
 7   days_since_prior_order  1384706 non-null  float64
 8   product_id              1384706 non-null  int64
 9   add_to_cart_order       1384706 non-null  int64
 10  reordered               1384706 non-null  int64
 11  product_name            1383473 non-null  str
 12  aisle_id                1384618 non-null  float64
 13  department_id           1384618 non-null  float64
 14  prices                  1384618 non-null  float64
 15  department              1384618 non-null  str
 16  aisle                   1384618 non-null  str
dtypes: float64(4), int64(9), str(4)
memory usage: 249.6 MB

In [24]:
df_train_analytic.shape

(1384706, 17)

In [25]:
df_customer_states = pd.read_csv("../data/processed/customer_states.csv")

In [26]:
df_train_analytics_final = df_train_analytic.merge(
    df_customer_states,
    on = 'user_id',
    how = 'left',
    # indicator=True
)
df_train_analytics_final.head()

,Unnamed: 0,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,10,1187899,1,train,11,4,8,14.0,196,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,10,1187899,1,train,11,4,8,14.0,25133,2,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,10,1187899,1,train,11,4,8,14.0,38928,3,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,10,1187899,1,train,11,4,8,14.0,26405,4,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,10,1187899,1,train,11,4,8,14.0,39657,5,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [27]:
# df_train_analytics_final["_merge"].value_counts()

In [28]:
df_train_analytics_final.drop(columns=['user_id', 'eval_set', 'product_id', 'aisle_id', 'department_id'], inplace = True)

In [29]:
print(df_train_analytics_final.shape)
df_train_analytics_final.head()

(1384706, 23)

,Unnamed: 0,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,...,Surnam,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,10,1187899,11,4,8,14.0,1,1,Soda,9.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,10,1187899,11,4,8,14.0,2,1,Organic String Cheese,8.6,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,10,1187899,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,10,1187899,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,10,1187899,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [30]:
df_train_analytics_final.drop(columns="Unnamed: 0", inplace=True)

In [33]:
df_train_analytics_final.to_parquet("../data/processed/instacart.parquet", index = False)

In [35]:
df_train_analytics_final.to_csv("../data/processed/instacart.csv", index = False)