#### datetime Module

In [1]:
from datetime import datetime, date, timedelta

#### Creating a Date Object

In [2]:
simple_date = date(2024, 7, 1)
simple_date

datetime.date(2024, 7, 1)

#### Creating a Datetime Object

In [3]:
full_datetime = datetime(2024, 7, 1, 14, 30, 0)
full_datetime

datetime.datetime(2024, 7, 1, 14, 30)

#### Getting the Current Date and Time

In [4]:
today = date.today()
now = datetime.now()

print(f'today is {today}')
print(f'right now is {now}')

today is 2026-04-03
right now is 2026-04-03 17:31:23.162802

#### Accessing Parts of a Datetime

In [5]:
print(f"Year: {full_datetime.year}")
print(f"Month: {full_datetime.month}")
print(f"Day: {full_datetime.day}")
print(f"Hour: {full_datetime.hour}")
print(f"Minute: {full_datetime.minute}")
print(f"Second: {full_datetime.second}")

Year: 2024
Month: 7
Day: 1
Hour: 14
Minute: 30
Second: 0

#### Formatting Dates as Strings

In [6]:
full_datetime.strftime("%Y-%m-%d")

'2024-07-01'

In [7]:
full_datetime.strftime("%d/%m/%Y")

'01/07/2024'

In [8]:
full_datetime.strftime("%B %d, %Y")

'July 01, 2024'

#### Parsing Strings into Datetime

In [9]:
dt = datetime.strptime("2024-07-01", "%Y-%m-%d")
dt

datetime.datetime(2024, 7, 1, 0, 0)

#### Arithmetic with Dates

In [10]:
start = date(2024, 7, 1)
end = date(2024, 7, 15)

delta = end - start
delta

datetime.timedelta(days=14)

In [11]:
delta.days

14

In [12]:
start + timedelta(days=10)

datetime.date(2024, 7, 11)

In [13]:
start - timedelta(days=7)

datetime.date(2024, 6, 24)

In [14]:
print(start + timedelta(days=10))
print(start - timedelta(days=7))
print(start + timedelta(weeks=2))
print(start - timedelta(weeks=1))

2024-07-11
2024-06-24
2024-07-15
2024-06-24

In [15]:
start_dt = datetime(2024, 7, 1, 14, 30, 0)

print(start_dt + timedelta(days=1))
print(start_dt + timedelta(hours=5))
print(start_dt + timedelta(minutes=45))
print(start_dt + timedelta(seconds=30))
print(start_dt + timedelta(days=2, hours=3, minutes=15, seconds=10))

2024-07-02 14:30:00
2024-07-01 19:30:00
2024-07-01 15:15:00
2024-07-01 14:30:30
2024-07-03 17:45:10

#### Dates in Pandas

In [16]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [17]:
df_dates.dtypes

customer_id      int64
signup_date        str
last_purchase      str
dtype: object

#### Converting to Datetime

In [18]:
df_dates["signup_date"] = pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])

df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [19]:
# Year, Month, and Day
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day
0,101,2024-01-15,2024-06-01,2024,1,15
1,102,2024-02-20,2024-06-15,2024,2,20
2,103,2024-03-05,2024-07-01,2024,3,5
3,104,2024-03-18,2024-07-08,2024,3,18
4,105,2024-04-10,2024-07-12,2024,4,10

In [20]:
# Month Name and Day Name
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()

df_dates[["signup_date", "signup_month_name", "signup_day_name"]]

  signup_date signup_month_name signup_day_name
0  2024-01-15           January          Monday
1  2024-02-20          February         Tuesday
2  2024-03-05             March         Tuesday
3  2024-03-18             March          Monday
4  2024-04-10             April       Wednesday

In [21]:
# Quarter
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates[["signup_date", "signup_quarter"]]

  signup_date  signup_quarter
0  2024-01-15               1
1  2024-02-20               1
2  2024-03-05               1
3  2024-03-18               1
4  2024-04-10               2

In [22]:
# Day of Week
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek
df_dates[["signup_date", "signup_dow"]]

  signup_date  signup_dow
0  2024-01-15           0
1  2024-02-20           1
2  2024-03-05           1
3  2024-03-18           0
4  2024-04-10           2

In [23]:
# Weekend Flag
df_dates["is_weekend"] = (df_dates["signup_date"].dt.dayofweek >= 5).astype(int)
df_dates[["signup_date", "signup_dow", "is_weekend"]]

  signup_date  signup_dow  is_weekend
0  2024-01-15           0           0
1  2024-02-20           1           0
2  2024-03-05           1           0
3  2024-03-18           0           0
4  2024-04-10           2           0

In [24]:
# Calculating Differences Between Dates
df_dates["days_between_signup_and_purchase"] = (
    df_dates["last_purchase"] - df_dates["signup_date"]
).dt.days

df_dates[["signup_date", "last_purchase", "days_between_signup_and_purchase"]]

  signup_date last_purchase  days_between_signup_and_purchase
0  2024-01-15    2024-06-01                               138
1  2024-02-20    2024-06-15                               116
2  2024-03-05    2024-07-01                               118
3  2024-03-18    2024-07-08                               112
4  2024-04-10    2024-07-12                                93

#### Filtering by Date Conditions

In [25]:
# Filter Rows After a Given Date
df_dates[df_dates["signup_date"] >= "2024-03-01"]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [26]:
# Filter a Specific Month
df_dates[df_dates["signup_date"].dt.month == 3]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112

In [27]:
# Filter a Specific Year
df_dates[df_dates["signup_date"].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

#### Sorting by Date

In [28]:
df_dates.sort_values("signup_date")

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

#### Creating Date Ranges

In [29]:
# Daily Date Range
pd.date_range(start="2024-07-01", periods=7, freq="D")

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07'],
              dtype='datetime64[us]', freq='D')

In [30]:
# Monthly Date Range
pd.date_range(start="2024-01-01", periods=6, freq="MS")

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01'],
              dtype='datetime64[us]', freq='MS')

#### Begining and the End of Month

In [31]:
some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [32]:
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.start_time
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.end_time

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,2024-01-31 23:59:59.999999,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2024-02-29 23:59:59.999999,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,2024-03-31 23:59:59.999999,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,2024-03-31 23:59:59.999999,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,2024-04-30 23:59:59.999999,10,April,Wednesday,2,2,0,93

#### Homework

#### Task 1 | Create a date Object and name it my_date

In [33]:
my_data = date(2025, 3, 15)

print(f"Full Value: {my_data}")
print(f"Year: {my_data.year}")
print(f"Month: {my_data.month}")
print(f"Day: {my_data.day}")

Full Value: 2025-03-15
Year: 2025
Month: 3
Day: 15

#### Task 2 | Create a datetime Object and name it meeting_time

In [34]:
meeting_time = datetime(2025, 10, 8, 16, 45, 30)

print(f"Year: {meeting_time.year}")
print(f"Month: {meeting_time.month}")
print(f"Day: {meeting_time.day}")
print(f"Hour: {meeting_time.hour}")
print(f"Minute: {meeting_time.minute}")
print(f"Second: {meeting_time.second}")

Year: 2025
Month: 10
Day: 8
Hour: 16
Minute: 45
Second: 30

#### Task 3 | Format Dates as Strings using meeting_time, display the date in the following formats

In [35]:
meeting_time.strftime("%Y-%m-%d")

'2025-10-08'

In [36]:
meeting_time.strftime("%d/%m/%Y")

'08/10/2025'

In [37]:
meeting_time.strftime("%B, %d, %Y")

'October, 08, 2025'

#### Task 4 | Parse a String into a Datetime

In [38]:
dt = datetime.strptime("2025-12-31", "%Y-%m-%d")
print(f"Parsed datetime: {dt}")

Parsed datetime: 2025-12-31 00:00:00

#### Task 5 | Parse a String into a Datetime

In [39]:
start = date(2025, 1, 10)
end = date(2025, 2, 5)

difference = end - start
difference

datetime.timedelta(days=26)

#### Task 6 | Work with timedelta Using start, calculate and print with f-strings

In [40]:
print(f"10 days after: {start + timedelta(days=10)}")
print(f"14 days before: {start - timedelta(days=14)}")
print(f"3 weeks after: {start + timedelta(weeks=3)}")

10 days after: 2025-01-20
14 days before: 2024-12-27
3 weeks after: 2025-01-31

In [41]:
dt = datetime(2025, 1, 10, 12, 0, 0)

In [42]:
new_dt = dt + timedelta(hours=5, minutes=20, seconds=45)
new_dt

datetime.datetime(2025, 1, 10, 17, 20, 45)

#### Practice with Pandas Dates

In [43]:
# Create a DataFrame with Date Strings
df_dates = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5],
    "signup_date": ["2024-01-10", "2024-02-05", "2024-03-12", "2024-04-01", "2024-05-20"],
    "last_purchase" : ["2024-02-15", "2024-03-01", "2024-03-28", "2024-05-10", "2024-06-25"]
})

df_dates

   customer_id signup_date last_purchase
0            1  2024-01-10    2024-02-15
1            2  2024-02-05    2024-03-01
2            3  2024-03-12    2024-03-28
3            4  2024-04-01    2024-05-10
4            5  2024-05-20    2024-06-25

In [44]:
# Check the data types of all columns
df_dates.dtypes

customer_id      int64
signup_date        str
last_purchase      str
dtype: object

In [45]:
# Convert String Columns to Datetime
df_dates["signup_date"] = pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])
df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [46]:
# Extract Date Components
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday

In [47]:
# Create a Day-of-Week and Weekend Flag
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek
df_dates["is_weekend"] = (df_dates["signup_dow"] >= 5).astype(int)
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday,2,0
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday,0,0
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,0
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday,0,0
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday,0,0

In [48]:
df_dates["days_between_signup_and_purchase"] = (
    df_dates["last_purchase"] - df_dates["signup_date"]
).dt.days
df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday,2,0,36
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday,0,0,25
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,0,16
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday,0,0,39
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday,0,0,36

In [49]:
# Filter Data
df_dates[df_dates["signup_date"] >= '2024-03-01']

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,0,16
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday,0,0,39
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday,0,0,36

In [50]:
df_dates[df_dates["signup_date"].dt.month == 3]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,0,16

In [51]:
df_dates[df_dates["signup_date"].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday,2,0,36
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday,0,0,25
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,0,16
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday,0,0,39
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday,0,0,36

In [52]:
df_dates.sort_values("signup_date")

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase
0,1,2024-01-10,2024-02-15,2024,1,10,1,January,Wednesday,2,0,36
1,2,2024-02-05,2024-03-01,2024,2,5,1,February,Monday,0,0,25
2,3,2024-03-12,2024-03-28,2024,3,12,1,March,Tuesday,1,0,16
3,4,2024-04-01,2024-05-10,2024,4,1,2,April,Monday,0,0,39
4,5,2024-05-20,2024-06-25,2024,5,20,2,May,Monday,0,0,36

In [53]:
pd.date_range(start="2024-07-01", periods=10, freq="D")

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07', '2024-07-08',
               '2024-07-09', '2024-07-10'],
              dtype='datetime64[us]', freq='D')

In [54]:
pd.date_range(start="2024-01-01", periods=12, freq="MS")

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01', '2024-11-01', '2024-12-01'],
              dtype='datetime64[us]', freq='MS')

In [55]:
# Create a DataFrame with

df_dates2 = pd.DataFrame({
    "date": pd.date_range(start="2024-01-01", periods=15, freq="D"),
    "sales": [100, 120, 130, 90, 150, 170, 160, 180, 200, 210, 190, 220, 230, 240, 250]
})

df_dates2

         date  sales
0  2024-01-01    100
1  2024-01-02    120
2  2024-01-03    130
3  2024-01-04     90
4  2024-01-05    150
5  2024-01-06    170
6  2024-01-07    160
7  2024-01-08    180
8  2024-01-09    200
9  2024-01-10    210
10 2024-01-11    190
11 2024-01-12    220
12 2024-01-13    230
13 2024-01-14    240
14 2024-01-15    250

In [56]:
df_dates2.dtypes

date     datetime64[us]
sales             int64
dtype: object

In [57]:
df_dates2["year"] = df_dates2["date"].dt.year
df_dates2["month"] = df_dates2["date"].dt.month
df_dates2["day"] = df_dates2["date"].dt.day
df_dates2["day_name"] = df_dates2["date"].dt.day_name()
df_dates2["dow"] = df_dates2["date"].dt.dayofweek
df_dates2["is_weekend"] = (df_dates2["dow"] >= 5).astype(int)

df_dates2

         date  sales  year  month  day   day_name  dow  is_weekend
0  2024-01-01    100  2024      1    1     Monday    0           0
1  2024-01-02    120  2024      1    2    Tuesday    1           0
2  2024-01-03    130  2024      1    3  Wednesday    2           0
3  2024-01-04     90  2024      1    4   Thursday    3           0
4  2024-01-05    150  2024      1    5     Friday    4           0
5  2024-01-06    170  2024      1    6   Saturday    5           1
6  2024-01-07    160  2024      1    7     Sunday    6           1
7  2024-01-08    180  2024      1    8     Monday    0           0
8  2024-01-09    200  2024      1    9    Tuesday    1           0
9  2024-01-10    210  2024      1   10  Wednesday    2           0
10 2024-01-11    190  2024      1   11   Thursday    3           0
11 2024-01-12    220  2024      1   12     Friday    4           0
12 2024-01-13    230  2024      1   13   Saturday    5           1
13 2024-01-14    240  2024      1   14     Sunday    6           1
14 2024-01-15    250  2024      1   15     Monday    0           0

In [68]:
# Beginning and End of Month for One Date
some_date = pd.Timestamp("2024-08-18")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")
print(f"Beginning of month (date only): {some_date.to_period('M').start_time.date()}")
print(f"End of month (date only): {some_date.to_period('M').end_time.date()}")

Original date: 2024-08-18 00:00:00
Beginning of month: 2024-08-01 00:00:00
End of month: 2024-08-31 23:59:59.999999
Beginning of month (date only): 2024-08-01
End of month (date only): 2024-08-31

In [81]:
# Beginning and End of Month for a Full ColumnUsing the signup_date column in your DataFrame, create two new columns:
df_dates["month_start"] = df_dates["signup_date"].dt.to_period("M").dt.start_time
df_dates["month_end"] = df_dates["signup_date"].dt.to_period("M").dt.end_time

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_quarter,signup_month_name,signup_day_name,signup_dow,is_weekend,days_between_signup_and_purchase,month_start,month_end
0,1,2024-01-10,2024-02-15,2024,2024-01-01,10,1,January,Wednesday,2,0,36,2024-01-01,2024-01-31 23:59:59.999999
1,2,2024-02-05,2024-03-01,2024,2024-02-01,5,1,February,Monday,0,0,25,2024-02-01,2024-02-29 23:59:59.999999
2,3,2024-03-12,2024-03-28,2024,2024-03-01,12,1,March,Tuesday,1,0,16,2024-03-01,2024-03-31 23:59:59.999999
3,4,2024-04-01,2024-05-10,2024,2024-04-01,1,2,April,Monday,0,0,39,2024-04-01,2024-04-30 23:59:59.999999
4,5,2024-05-20,2024-06-25,2024,2024-05-01,20,2,May,Monday,0,0,36,2024-05-01,2024-05-31 23:59:59.999999