#### Part 1: Geographic Foundations

In [1]:
# Import Libraries
import os
import zipfile
import requests
import numpy as np
import pandas as pd
import plotly.express as px
import folium

from tqdm import tqdm
from pathlib import Path

#### Demo Trip DF

In [2]:
trip_demo = pd.DataFrame({
    "ride_id": list(range(1, 21)),

    "start_station": [
        "Station A", "Station A", "Station A", "Station A", "Station A",
        "Station B", "Station B", "Station B", "Station B",
        "Station C", "Station C", "Station C",
        "Station D", "Station D", "Station D",
        "Station E", "Station E",
        "Station A", "Station B", "Station C"
    ],

    "end_station": [
        "Station B", "Station B", "Station B", "Station C", "Station C",
        "Station A", "Station A", "Station C", "Station D",
        "Station A", "Station B", "Station E",
        "Station A", "Station C", "Station E",
        "Station A", "Station D",
        "Station E", "Station E", "Station D"
    ],

    "started_at": pd.to_datetime([
        "2025-01-01 08:00", "2025-01-01 08:15", "2025-01-01 08:30",
        "2025-01-01 09:00", "2025-01-01 09:20",
        "2025-01-01 10:00", "2025-01-01 10:15", "2025-01-01 10:40",
        "2025-01-01 11:00",
        "2025-01-01 11:30", "2025-01-01 12:00", "2025-01-01 12:20",
        "2025-01-01 13:00", "2025-01-01 13:30", "2025-01-01 14:00",
        "2025-01-01 14:30", "2025-01-01 15:00",
        "2025-01-01 15:30", "2025-01-01 16:00", "2025-01-01 16:30"
    ]),

    "ended_at": pd.to_datetime([
        "2025-01-01 08:10", "2025-01-01 08:28", "2025-01-01 08:42",
        "2025-01-01 09:18", "2025-01-01 09:35",
        "2025-01-01 10:12", "2025-01-01 10:30", "2025-01-01 10:55",
        "2025-01-01 11:18",
        "2025-01-01 11:48", "2025-01-01 12:14", "2025-01-01 12:45",
        "2025-01-01 13:20", "2025-01-01 13:48", "2025-01-01 14:20",
        "2025-01-01 14:55", "2025-01-01 15:22",
        "2025-01-01 15:58", "2025-01-01 16:25", "2025-01-01 16:50"
    ]),

    "member_casual": [
        "member", "member", "casual", "member", "casual",
        "member", "member", "casual", "member",
        "casual", "member", "casual",
        "member", "casual", "member",
        "casual", "member",
        "member", "casual", "member"
    ]
})

trip_demo

,ride_id,start_station,end_station,started_at,ended_at,member_casual
0,1,Station A,Station B,2025-01-01 08:00:00,2025-01-01 08:10:00,member
1,2,Station A,Station B,2025-01-01 08:15:00,2025-01-01 08:28:00,member
2,3,Station A,Station B,2025-01-01 08:30:00,2025-01-01 08:42:00,casual
3,4,Station A,Station C,2025-01-01 09:00:00,2025-01-01 09:18:00,member
4,5,Station A,Station C,2025-01-01 09:20:00,2025-01-01 09:35:00,casual
5,6,Station B,Station A,2025-01-01 10:00:00,2025-01-01 10:12:00,member
6,7,Station B,Station A,2025-01-01 10:15:00,2025-01-01 10:30:00,member
7,8,Station B,Station C,2025-01-01 10:40:00,2025-01-01 10:55:00,casual
8,9,Station B,Station D,2025-01-01 11:00:00,2025-01-01 11:18:00,member
9,10,Station C,Station A,2025-01-01 11:30:00,2025-01-01 11:48:00,casual
10,11,Station C,Station B,2025-01-01 12:00:00,2025-01-01 12:14:00,member
11,12,Station C,Station E,2025-01-01 12:20:00,2025-01-01 12:45:00,casual
12,13,Station D,Station A,2025-01-01 13:00:00,2025-01-01 13:20:00,member
13,14,Station D,Station C,2025-01-01 13:30:00,2025-01-01 13:48:00,casual
14,15,Station D,Station E,2025-01-01 14:00:00,2025-01-01 14:20:00,member
15,16,Station E,Station A,2025-01-01 14:30:00,2025-01-01 14:55:00,casual
16,17,Station E,Station D,2025-01-01 15:00:00,2025-01-01 15:22:00,member
17,18,Station A,Station E,2025-01-01 15:30:00,2025-01-01 15:58:00,member
18,19,Station B,Station E,2025-01-01 16:00:00,2025-01-01 16:25:00,casual
19,20,Station C,Station D,2025-01-01 16:30:00,2025-01-01 16:50:00,member

#### Add Station Coordinates

In [3]:
station_coordinates = pd.DataFrame({
    "station": [
        "Station A",
        "Station B",
        "Station C",
        "Station D",
        "Station E"
    ],
    "lat": [
        40.735,
        40.751,
        40.742,
        40.728,
        40.760
    ],
    "lng": [
        -73.991,
        -73.977,
        -73.985,
        -73.970,
        -73.995
    ]
})

station_coordinates

     station     lat     lng
0  Station A  40.735 -73.991
1  Station B  40.751 -73.977
2  Station C  40.742 -73.985
3  Station D  40.728 -73.970
4  Station E  40.760 -73.995

In [4]:
trip_demo = (
    trip_demo
    .merge(
        station_coordinates,
        left_on="start_station",
        right_on="station",
        how="left"
    )
    .rename(columns={
        "lat": "start_lat",
        "lng": "start_lng"
    })
    .drop(columns="station")
    .merge(
        station_coordinates,
        left_on="end_station",
        right_on="station",
        how="left"
    )
    .rename(columns={
        "lat": "end_lat",
        "lng": "end_lng"
    })
    .drop(columns="station")
)

trip_demo.head()

,ride_id,start_station,end_station,started_at,ended_at,member_casual,start_lat,start_lng,end_lat,end_lng
0,1,Station A,Station B,2025-01-01 08:00:00,2025-01-01 08:10:00,member,40.735,-73.991,40.751,-73.977
1,2,Station A,Station B,2025-01-01 08:15:00,2025-01-01 08:28:00,member,40.735,-73.991,40.751,-73.977
2,3,Station A,Station B,2025-01-01 08:30:00,2025-01-01 08:42:00,casual,40.735,-73.991,40.751,-73.977
3,4,Station A,Station C,2025-01-01 09:00:00,2025-01-01 09:18:00,member,40.735,-73.991,40.742,-73.985
4,5,Station A,Station C,2025-01-01 09:20:00,2025-01-01 09:35:00,casual,40.735,-73.991,40.742,-73.985

#### Map center

In [5]:
map_center = [
    pd.concat([trip_demo["start_lat"], trip_demo["end_lat"]]).mean(),
    pd.concat([trip_demo["start_lng"], trip_demo["end_lng"]]).mean()
]

map_center

[np.float64(40.7427), np.float64(-73.9841)]

#### Adding Duration

In [6]:
trip_demo["duration_min"] = (
    trip_demo["ended_at"] - trip_demo["started_at"]
).dt.total_seconds() / 60

trip_demo[[
    "ride_id",
    "start_station",
    "end_station",
    "started_at",
    "ended_at",
    "duration_min"
]].head()

,ride_id,start_station,end_station,started_at,ended_at,duration_min
0,1,Station A,Station B,2025-01-01 08:00:00,2025-01-01 08:10:00,10.0
1,2,Station A,Station B,2025-01-01 08:15:00,2025-01-01 08:28:00,13.0
2,3,Station A,Station B,2025-01-01 08:30:00,2025-01-01 08:42:00,12.0
3,4,Station A,Station C,2025-01-01 09:00:00,2025-01-01 09:18:00,18.0
4,5,Station A,Station C,2025-01-01 09:20:00,2025-01-01 09:35:00,15.0

#### Adding Time Features

In [7]:
trip_demo["date"] = trip_demo['started_at'].dt.date
trip_demo["hour"] = trip_demo["started_at"].dt.hour
trip_demo["day_name"] = trip_demo["started_at"].dt.day_name()
trip_demo["month_name"] = trip_demo["started_at"].dt.month_name()

trip_demo.head()

,ride_id,start_station,end_station,started_at,ended_at,member_casual,start_lat,start_lng,end_lat,end_lng,duration_min,date,hour,day_name,month_name
0,1,Station A,Station B,2025-01-01 08:00:00,2025-01-01 08:10:00,member,40.735,-73.991,40.751,-73.977,10.0,2025-01-01,8,Wednesday,January
1,2,Station A,Station B,2025-01-01 08:15:00,2025-01-01 08:28:00,member,40.735,-73.991,40.751,-73.977,13.0,2025-01-01,8,Wednesday,January
2,3,Station A,Station B,2025-01-01 08:30:00,2025-01-01 08:42:00,casual,40.735,-73.991,40.751,-73.977,12.0,2025-01-01,8,Wednesday,January
3,4,Station A,Station C,2025-01-01 09:00:00,2025-01-01 09:18:00,member,40.735,-73.991,40.742,-73.985,18.0,2025-01-01,9,Wednesday,January
4,5,Station A,Station C,2025-01-01 09:20:00,2025-01-01 09:35:00,casual,40.735,-73.991,40.742,-73.985,15.0,2025-01-01,9,Wednesday,January

#### Visualizing Points with Folium

In [8]:
# m = folium.Map(
#     location=[40.74, -73.99]
#     zoom_start=13
# )

#### Citi Bike | Jersey

In [9]:
#| echo: true
# Step 1: Define the Data Source
CITIBIKE_INDEX_URL = "https://s3.amazonaws.com/tripdata"
OUTPUT_DIR = "../data/citibike"
PERIOD = "202510"

In [10]:
# Step 2: Download Jersey Data
# eval: true
from pathlib import Path
from urllib.request import urlretrieve
from zipfile import ZipFile

file_name = f"JC-{PERIOD}-citibike-tripdata.zip"

output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(exist_ok=True)

zip_path = output_dir / file_name


## Dowloading the Zip file
url = f"{CITIBIKE_INDEX_URL}/{file_name}"

print(f"Downloading: {url}")
urlretrieve(url, zip_path)

print(f"Saved ZIP file to: {zip_path}")


with ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(output_dir)

print(f"Extracted files into: {output_dir}")

Downloading: https://s3.amazonaws.com/tripdata/JC-202510-citibike-tripdata.zip
Saved ZIP file to: ..\data\citibike\JC-202510-citibike-tripdata.zip
Extracted files into: ..\data\citibike

In [11]:
zip_path.unlink()
print("ZIP file removed")

ZIP file removed

In [12]:
# Step 3: Read the data
file_name = 'JC-202510-citibike-tripdata.csv'
citibike_202510 = pd.read_csv(f'{output_dir}/{file_name}')
citibike_202510.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,929852F0DC04F49C,electric_bike,2025-10-08 06:59:53.767,2025-10-08 07:04:08.012,Warren St,JC006,Essex Light Rail,NaN,40.721124,-74.038051,NaN,NaN,member
1,7E6F8FADF45B1D8E,electric_bike,2025-10-08 08:13:15.096,2025-10-08 08:18:16.168,Newark Ave,JC032,Essex Light Rail,NaN,40.721525,-74.046305,NaN,NaN,member
2,9B679869FCA8F845,electric_bike,2025-10-09 10:10:26.020,2025-10-09 10:20:08.505,Liberty Light Rail,JC052,Newport PATH,NaN,40.711242,-74.055701,NaN,NaN,member
3,E2051DD457BC4076,electric_bike,2025-10-09 11:34:22.937,2025-10-09 11:48:49.501,Hoboken Ave at Monmouth St,JC105,Newport PATH,NaN,40.735208,-74.046964,NaN,NaN,member
4,239AC07371E414EC,electric_bike,2025-10-23 19:24:16.237,2025-10-23 19:28:22.592,Union St & Bergen Ave,JC122,Garfield Light Rail,JC119,40.715750,-74.078870,40.710526,-74.070112,member

In [13]:
# Step 4: Downloading year 2025
def download_periods(year:list, start_m:int, stop_m:int)->list:
    """ 
    
    """
    YEAR = year
    MONTH = [str(i+1) if i+1>9 else "0" + str(i+1) for i in range(start_m, stop_m)]

    periods = []

    for i in YEAR:
        for j in MONTH:
            k = i+j
            periods.append(k)
    # print(periods)
    return periods

In [14]:
periods = download_periods(year = ['2025'], start_m = 1, stop_m = 12)

periods

['202502',
 '202503',
 '202504',
 '202505',
 '202506',
 '202507',
 '202508',
 '202509',
 '202510',
 '202511',
 '202512']

In [15]:
#| echo: true
#| eval: true
#| output: true
from pathlib import Path
from urllib.request import urlretrieve
from zipfile import ZipFile

BASE_URL = "https://s3.amazonaws.com/tripdata"
OUTPUT_DIR = "../data/citibike"
output_dir = Path(OUTPUT_DIR)
output_dir.mkdir(exist_ok=True)

periods = download_periods(['2025'],10,12)

print(periods)
for  period in periods:
    file_name = f"JC-{period}-citibike-tripdata.csv.zip"


    zip_path = output_dir / file_name
    url = f"{BASE_URL}/{file_name}"

    print("downloading form:  ", url)
    
    urlretrieve(url,zip_path)
    
    print("saving into:  ", zip_path)


    with ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(output_dir)


    print(f"Extracted files into: {output_dir}")

    zip_path.unlink()
    print("ZIP file removed.")

['202511', '202512']
downloading form:   https://s3.amazonaws.com/tripdata/JC-202511-citibike-tripdata.csv.zip
saving into:   ..\data\citibike\JC-202511-citibike-tripdata.csv.zip
Extracted files into: ..\data\citibike
ZIP file removed.
downloading form:   https://s3.amazonaws.com/tripdata/JC-202512-citibike-tripdata.csv.zip
saving into:   ..\data\citibike\JC-202512-citibike-tripdata.csv.zip
Extracted files into: ..\data\citibike
ZIP file removed.

In [17]:
import pandas as pd
URL = "https://raw.githubusercontent.com/hovhannisyan91/data_analytics_with_python/refs/heads/main/data/citibike"
PATH  = '../data/citibike'
csv_files = csv_files = [
'JC-202511-citibike-tripdata.csv',
 'JC-202507-citibike-tripdata.csv',
 'JC-202505-citibike-tripdata.csv',
 'JC-202503-citibike-tripdata.csv',
 'JC-202509-citibike-tripdata.csv',
 'JC-202501-citibike-tripdata.csv',
 'JC-202506-citibike-tripdata.csv',
 'JC-202510-citibike-tripdata.csv',
 'JC-202504-citibike-tripdata.csv',
 'JC-202512-citibike-tripdata.csv',
 'JC-202502-citibike-tripdata.csv',
 'JC-202508-citibike-tripdata.csv']


for i in csv_files:
    df = pd.read_csv(f"{URL}/{i}")
    df.to_csv(f"{PATH}/{i}", index=False)
    # print(f"{URL} saved in {URLpath} | shape: {df.shape}")

#### Checking One

In [2]:
import glob
import numpy as np
import pandas as pd

file_names = glob.glob('../data/citibike//*.csv')
file_names

['../data/citibike\\JC-202501-citibike-tripdata.csv',
 '../data/citibike\\JC-202502-citibike-tripdata.csv',
 '../data/citibike\\JC-202503-citibike-tripdata.csv',
 '../data/citibike\\JC-202504-citibike-tripdata.csv',
 '../data/citibike\\JC-202505-citibike-tripdata.csv',
 '../data/citibike\\JC-202506-citibike-tripdata.csv',
 '../data/citibike\\JC-202507-citibike-tripdata.csv',
 '../data/citibike\\JC-202508-citibike-tripdata.csv',
 '../data/citibike\\JC-202509-citibike-tripdata.csv',
 '../data/citibike\\JC-202510-citibike-tripdata.csv',
 '../data/citibike\\JC-202511-citibike-tripdata.csv',
 '../data/citibike\\JC-202512-citibike-tripdata.csv']

In [3]:
len(file_names)

12

In [4]:
dfs = []
cols = []
for file_name in file_names:
    df = pd.read_csv(file_name)
    print(file_name)
    print(df.columns, 2*"||", len(df.columns))

    cols.append(list(df.columns))
    dfs.append(df)

../data/citibike\JC-202501-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202502-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202503-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202504-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202505-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202506-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202507-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202508-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202509-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202510-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202511-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13
../data/citibike\JC-202512-citibike-tripdata.csv
Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str') |||| 13

In [8]:
citibike_df = pd.concat(dfs)
citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member

In [9]:
citibike_df.info()

<class 'pandas.DataFrame'>
Index: 1002704 entries, 0 to 48473
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   ride_id             1002704 non-null  str
 1   rideable_type       1002704 non-null  str
 2   started_at          1002704 non-null  str
 3   ended_at            1002704 non-null  str
 4   start_station_name  1002701 non-null  str
 5   start_station_id    1002701 non-null  str
 6   end_station_name    999469 non-null   str
 7   end_station_id      998307 non-null   str
 8   start_lat           1002702 non-null  float64
 9   start_lng           1002702 non-null  float64
 10  end_lat             999260 non-null   float64
 11  end_lng             999260 non-null   float64
 12  member_casual       1002704 non-null  str
dtypes: float64(4), str(9)
memory usage: 230.1 MB

In [10]:
citibike_df.shape

(1002704, 13)

#### Step 6: Setting Dates

In [12]:
citibike_df['started_at'] = pd.to_datetime(citibike_df['started_at'], errors='coerce')
citibike_df['ended_at'] = pd.to_datetime(citibike_df['ended_at'], errors="coerce")

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member

In [13]:
citibike_df.info()

<class 'pandas.DataFrame'>
Index: 1002704 entries, 0 to 48473
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   ride_id             1002704 non-null  str
 1   rideable_type       1002704 non-null  str
 2   started_at          1002704 non-null  datetime64[us]
 3   ended_at            1002704 non-null  datetime64[us]
 4   start_station_name  1002701 non-null  str
 5   start_station_id    1002701 non-null  str
 6   end_station_name    999469 non-null   str
 7   end_station_id      998307 non-null   str
 8   start_lat           1002702 non-null  float64
 9   start_lng           1002702 non-null  float64
 10  end_lat             999260 non-null   float64
 11  end_lng             999260 non-null   float64
 12  member_casual       1002704 non-null  str
dtypes: datetime64[us](2), float64(4), str(7)
memory usage: 186.1 MB

#### Step 7: df overview

In [14]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

#### Step 8: Missing Values

In [16]:
missing_values = (
    citibike_df
    .isna()
    .sum()
    .reset_index()
)

missing_values.columns = ["column", "missing_count"]

missing_values["missing_share"] = (
    missing_values["missing_count"] / len(citibike_df)
)

missing_values.sort_values("missing_count", ascending=False)

                column  missing_count  missing_share
7       end_station_id           4397       0.004385
10             end_lat           3444       0.003435
11             end_lng           3444       0.003435
6     end_station_name           3235       0.003226
4   start_station_name              3       0.000003
5     start_station_id              3       0.000003
8            start_lat              2       0.000002
9            start_lng              2       0.000002
0              ride_id              0       0.000000
3             ended_at              0       0.000000
2           started_at              0       0.000000
1        rideable_type              0       0.000000
12       member_casual              0       0.000000

In [17]:
citibike_df = citibike_df.dropna(
    subset=[
        "ride_id",
        "started_at",
        "ended_at",
        "start_lat",
        "start_lng",
        "end_lat",
        "end_lng"
    ]
)

In [18]:
citibike_df.shape

(999258, 13)

#### Ride Duration

In [19]:
citibike_df["ride_duration_minutes"] = (
    citibike_df["ended_at"] - citibike_df["started_at"]
).dt.total_seconds() / 60

In [20]:
citibike_df = citibike_df[
    (citibike_df["ride_duration_minutes"] > 1) & 
    (citibike_df["ride_duration_minutes"] <= 24 * 60) 
].copy()

In [21]:
citibike_df.shape

(999225, 14)

In [22]:
citibike_df["date"] = citibike_df["started_at"].dt.date
citibike_df["month"] = citibike_df["started_at"].dt.to_period("M").astype(str)
citibike_df["month_name"] = citibike_df["started_at"].dt.month_name()
citibike_df["day_of_week"] = citibike_df["started_at"].dt.day_name()
citibike_df["hour"] = citibike_df["started_at"].dt.hour

In [23]:
def assign_season(month_number):
    if month_number in [12, 1, 2]:
        return "Winter"
    elif month_number in [3, 4, 5]:
        return "Spring"
    elif month_number in [6, 7, 8]:
        return "Summer"
    else:
        return "Autumn"


citibike_df["season"] = (
    citibike_df["started_at"]
    .dt.month
    .apply(assign_season)
)

In [24]:
citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_duration_minutes,date,month,month_name,day_of_week,hour,season
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member,6.192900,2025-01-16,2025-01,January,Thursday,17,Winter
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member,11.461350,2025-01-31,2025-01,January,Friday,6,Winter
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,21.377617,2025-01-09,2025-01,January,Thursday,16,Winter
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,22.934333,2025-01-21,2025-01,January,Tuesday,16,Winter
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member,25.822100,2025-01-30,2025-01,January,Thursday,16,Winter

In [25]:
citibike_df.to_csv('../data/citibike/JC/JC2025_Enriched.csv', index=False)

In [26]:
citibike_df.shape

(999225, 20)

In [27]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'ride_duration_minutes', 'date', 'month', 'month_name',
       'day_of_week', 'hour', 'season'],
      dtype='str')

In [28]:
citibike_df[
    [
        "started_at",
        "date",
        "month",
        "month_name",
        "day_of_week",
        "hour",
        "season"
    ]
].head()

,started_at,date,month,month_name,day_of_week,hour,season
0,2025-01-16 17:50:49.136,2025-01-16,2025-01,January,Thursday,17,Winter
1,2025-01-31 06:10:41.818,2025-01-31,2025-01,January,Friday,6,Winter
2,2025-01-09 16:42:50.213,2025-01-09,2025-01,January,Thursday,16,Winter
3,2025-01-21 16:14:14.398,2025-01-21,2025-01,January,Tuesday,16,Winter
4,2025-01-30 16:38:18.840,2025-01-30,2025-01,January,Thursday,16,Winter

In [31]:
monthly_rides = (
    citibike_df
    .groupby("month", as_index=False)
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

monthly_rides

      month  number_of_rides
0   2024-12                2
1   2025-01            50589
2   2025-02            45250
3   2025-03            73277
4   2025-04            81533
5   2025-05            93202
6   2025-06            96736
7   2025-07           107374
8   2025-08           108001
9   2025-09           115580
10  2025-10           103586
11  2025-11            76233
12  2025-12            47862

#### Step 11: Getting Weather Data

In [49]:
import pandas as pd
import requests

lat = 40.7178
lng = -74.0431

start_date = "2025-01-01"
end_date = "2025-12-31"

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": lat,
    "longitude": lng,
    "start_date": start_date,
    "end_date": end_date,
    "daily": [
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean",
        "precipitation_sum",
        "rain_sum",
        "snowfall_sum",
        "wind_speed_10m_max"
    ],
    "timezone": "America/New_York"
}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()

weather_daily = pd.DataFrame(data["daily"])
weather_daily["date"] = pd.to_datetime(weather_daily["time"])
weather_daily = weather_daily.drop(columns="time")

weather_daily.tail()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
360,-1.0,-7.3,-3.6,5.3,0.4,3.43,16.3,2025-12-27
361,1.0,-11.6,-5.8,0.9,0.9,0.00,9.4,2025-12-28
362,7.3,-1.4,3.5,3.9,3.9,0.00,23.8,2025-12-29
363,-0.2,-3.0,-1.3,0.0,0.0,0.00,25.5,2025-12-30
364,-0.2,-3.7,-2.2,0.0,0.0,0.00,16.5,2025-12-31

In [50]:
list(weather_daily.columns)

['temperature_2m_max',
 'temperature_2m_min',
 'temperature_2m_mean',
 'precipitation_sum',
 'rain_sum',
 'snowfall_sum',
 'wind_speed_10m_max',
 'date']

In [51]:
weather_daily = weather_daily[['date', 'temperature_2m_max', 'temperature_2m_min', 'temperature_2m_mean', 
                               'precipitation_sum', 'rain_sum', 'snowfall_sum', 'wind_speed_10m_max',]]

weather_daily.head()

,date,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2025-01-01,10.9,3.9,7.4,4.5,4.5,0.0,23.2
1,2025-01-02,5.4,0.3,2.6,0.0,0.0,0.0,25.1
2,2025-01-03,3.2,-1.9,0.4,0.0,0.0,0.0,17.1
3,2025-01-04,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1
4,2025-01-05,0.3,-3.6,-2.2,0.0,0.0,0.0,19.9

#### Whether Analytics

In [52]:
citibike_df.info()

<class 'pandas.DataFrame'>
Index: 999225 entries, 0 to 48473
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ride_id                999225 non-null  str
 1   rideable_type          999225 non-null  str
 2   started_at             999225 non-null  datetime64[us]
 3   ended_at               999225 non-null  datetime64[us]
 4   start_station_name     999224 non-null  str
 5   start_station_id       999224 non-null  str
 6   end_station_name       998439 non-null  str
 7   end_station_id         998282 non-null  str
 8   start_lat              999225 non-null  float64
 9   start_lng              999225 non-null  float64
 10  end_lat                999225 non-null  float64
 11  end_lng                999225 non-null  float64
 12  member_casual          999225 non-null  str
 13  ride_duration_minutes  999225 non-null  float64
 14  date                   999225 non-null  datetime64[s]
 15  month                  999225 non-null  str
 16  month_name             999225 non-null  str
 17  day_of_week            999225 non-null  str
 18  hour                   999225 non-null  int32
 19  season                 999225 non-null  str
dtypes: datetime64[s](1), datetime64[us](2), float64(5), int32(1), str(11)
memory usage: 260.6 MB

In [53]:
citibike_df['date'] = pd.to_datetime(citibike_df['date'], errors="coerce")

In [54]:
citibike_df.info()

<class 'pandas.DataFrame'>
Index: 999225 entries, 0 to 48473
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ride_id                999225 non-null  str
 1   rideable_type          999225 non-null  str
 2   started_at             999225 non-null  datetime64[us]
 3   ended_at               999225 non-null  datetime64[us]
 4   start_station_name     999224 non-null  str
 5   start_station_id       999224 non-null  str
 6   end_station_name       998439 non-null  str
 7   end_station_id         998282 non-null  str
 8   start_lat              999225 non-null  float64
 9   start_lng              999225 non-null  float64
 10  end_lat                999225 non-null  float64
 11  end_lng                999225 non-null  float64
 12  member_casual          999225 non-null  str
 13  ride_duration_minutes  999225 non-null  float64
 14  date                   999225 non-null  datetime64[s]
 15  month                  999225 non-null  str
 16  month_name             999225 non-null  str
 17  day_of_week            999225 non-null  str
 18  hour                   999225 non-null  int32
 19  season                 999225 non-null  str
dtypes: datetime64[s](1), datetime64[us](2), float64(5), int32(1), str(11)
memory usage: 260.6 MB

In [55]:
weather_daily.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   date                 365 non-null    datetime64[us]
 1   temperature_2m_max   365 non-null    float64
 2   temperature_2m_min   365 non-null    float64
 3   temperature_2m_mean  365 non-null    float64
 4   precipitation_sum    365 non-null    float64
 5   rain_sum             365 non-null    float64
 6   snowfall_sum         365 non-null    float64
 7   wind_speed_10m_max   365 non-null    float64
dtypes: datetime64[us](1), float64(7)
memory usage: 22.9 KB

#### Merging

In [56]:
daily_rides = (
    citibike_df
    .groupby("date", as_index=False)
    .agg(
        number_of_rides = ("ride_id", "count")
    )
)

daily_rides["date"] = pd.to_datetime(daily_rides["date"])
daily_rides

          date  number_of_rides
0   2024-12-31                2
1   2025-01-01             1179
2   2025-01-02             1710
3   2025-01-03             1770
4   2025-01-04             1337
..         ...              ...
361 2025-12-27              287
362 2025-12-28              488
363 2025-12-29              952
364 2025-12-30             1142
365 2025-12-31             1131

[366 rows x 2 columns]

In [57]:
bike_weather_daily = daily_rides.merge(
    weather_daily,
    on="date",
    how="left"
)
bike_weather_daily

,date,number_of_rides,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max
0,2024-12-31,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-01-01,1179,10.9,3.9,7.4,4.5,4.5,0.00,23.2
2,2025-01-02,1710,5.4,0.3,2.6,0.0,0.0,0.00,25.1
3,2025-01-03,1770,3.2,-1.9,0.4,0.0,0.0,0.00,17.1
4,2025-01-04,1337,-0.1,-2.7,-1.4,0.0,0.0,0.00,26.1
...,...,...,...,...,...,...,...,...,...
361,2025-12-27,287,-1.0,-7.3,-3.6,5.3,0.4,3.43,16.3
362,2025-12-28,488,1.0,-11.6,-5.8,0.9,0.9,0.00,9.4
363,2025-12-29,952,7.3,-1.4,3.5,3.9,3.9,0.00,23.8
364,2025-12-30,1142,-0.2,-3.0,-1.3,0.0,0.0,0.00,25.5
365,2025-12-31,1131,-0.2,-3.7,-2.2,0.0,0.0,0.00,16.5

In [58]:
fig = px.line(
    weather_daily,
    x="date",
    y="temperature_2m_mean",
    title="Daily Average Temperature Over Time",
    markers=False
)

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Average Temperature",
    hovermode="x unified"
)

fig.show()

In [60]:
fig = px.line(
    weather_daily,
    x="date",
    y="wind_speed_10m_max",
    title="Daily Maximum Wind Speed Over Time",
    markers=False
)

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Average Temperature",
    hovermode="x unified"
)

fig.show()

In [61]:
temperature_long = weather_daily.melt(
    id_vars= 'date',
    value_vars =  [
        "temperature_2m_max",
        "temperature_2m_min",
        "temperature_2m_mean"
    ],
    var_name =  "temperature_type",
    value_name = "temperature"
)

temperature_long

           date     temperature_type  temperature
0    2025-01-01   temperature_2m_max         10.9
1    2025-01-02   temperature_2m_max          5.4
2    2025-01-03   temperature_2m_max          3.2
3    2025-01-04   temperature_2m_max         -0.1
4    2025-01-05   temperature_2m_max          0.3
...         ...                  ...          ...
1090 2025-12-27  temperature_2m_mean         -3.6
1091 2025-12-28  temperature_2m_mean         -5.8
1092 2025-12-29  temperature_2m_mean          3.5
1093 2025-12-30  temperature_2m_mean         -1.3
1094 2025-12-31  temperature_2m_mean         -2.2

[1095 rows x 3 columns]

In [62]:
fig = px.line(
    temperature_long,
    x="date",
    y="temperature",
    color="temperature_type",
    title="Daily Temperature: Maximum, Minimum, and Average",
    markers=False
)

fig.update_layout(
    xaxis_title="Date",
    yaxis_title="Temperature",
    # hovermode="x unified"
)

fig.show()